Repository LuccaSA/RestDrivenDomain, pull requests merged in 2018-10, with the labels that each got.

#171 MOD : IStorageService moved to Application layer
  Application/RDD.Application/Controllers/AppController.cs
  Application/RDD.Application/IStorageService.cs
  Application/RDD.Application/RDD.Application.csproj
  Domain/RDD.Domain.Tests/Models/OpenRepository.cs
  Domain/RDD.Domain.Tests/Models/UsersAppController.cs
  Domain/RDD.Domain.Tests/QueryTests.cs
  Domain/RDD.Domain.Tests/Templates/SingleContextTests.cs
  Infra/RDD.Infra/RDD.Infra.csproj
  Infra/RDD.Infra/Storage/EFStorageService.cs
  Infra/RDD.Infra/Storage/InMemoryStorageService.cs
  Infra/RDD.Infra/Storage/ReadOnlyRepository.cs
  Infra/RDD.Infra/Storage/Repository.cs
  Web/RDD.Web.Tests/CollectionPropertiesTests.cs
  Web/RDD.Web.Tests/WebPagingTests.cs
  docs/CHANGELOG.md
Labels: bug, clean.code, release 3.0

#174 REF Tests
  Domain/RDD.Domain.Tests/AppControllerTests.cs
  Domain/RDD.Domain.Tests/CollectionMethodsTests.cs
  Domain/RDD.Domain.Tests/DefaultFixture.cs
  Domain/RDD.Domain.Tests/Models/User.cs
  Domain/RDD.Domain.Tests/Models/UserWithParameters.cs
  Domain/RDD.Domain.Tests/Models/UsersAppController.cs
  Domain/RDD.Domain.Tests/Models/UsersCollection.cs
  Domain/RDD.Domain.Tests/Models/UsersCollectionWithHardcodedGetById.cs
  Domain/RDD.Domain.Tests/OrderByConverterTests.cs
  Domain/RDD.Domain.Tests/PropertySelectorCollectionTests.cs
  Domain/RDD.Domain.Tests/QueryTests.cs
  Infra/RDD.Infra.Tests/CollectionTests.cs
  Infra/RDD.Infra.Tests/DatabaseTest.cs
  Infra/RDD.Infra.Tests/RDD.Infra.Tests.csproj
  Infra/RDD.Infra.Tests/UsersRepository.cs
  Web/RDD.Web.Tests/CollectionPropertiesTests.cs
  Web/RDD.Web.Tests/WebControllerTests.cs
  Web/RDD.Web.Tests/WebPagingTests.cs
Labels: clean.code, enhancement, release 3.0

#176 Fix.rdd.preview.bugs
  Domain/RDD.Domain.Tests/Members/TreeParserTests.cs
  Domain/RDD.Domain/AssemblyInfo.cs
  Domain/RDD.Domain/Helpers/Expressions/Utils/TreeParser.cs
  Domain/RDD.Domain/Patchers/ObjectPatcher.cs
  Web/RDD.Web.Tests/ServerMock/Startup.cs
  Web/RDD.Web.Tests/Services/ServicesCollectionTests.cs
  Web/RDD.Web/Helpers/RddServiceCollectionExtensions.cs
  docs/CHANGELOG.md
Labels: bug, release 3.0

#178 True serialize
  Web/RDD.Web.Tests/Models/MyValueObject.cs
  Web/RDD.Web.Tests/Models/UserWebController.cs
  Web/RDD.Web.Tests/Serialization/FieldsTests.cs
  Web/RDD.Web.Tests/Serialization/PropertySerializerTests.cs
  Web/RDD.Web.Tests/ServerMock/ExchangeRateController.cs
  Web/RDD.Web.Tests/ServerMock/Startup.cs
  Web/RDD.Web.Tests/Services/ServicesCollectionTests.cs
  Web/RDD.Web.Tests/WebControllerTests.cs
  Web/RDD.Web/AssemblyInfo.cs
  Web/RDD.Web/Controllers/ReadOnlyWebController.cs
  Web/RDD.Web/Controllers/WebController.cs
  Web/RDD.Web/Helpers/RddServiceCollectionExtensions.cs
  Web/RDD.Web/Models/Metadata.cs
  Web/RDD.Web/Models/MetadataHeader.cs
  Web/RDD.Web/Models/MetadataPaging.cs
  Web/RDD.Web/RDD.Web.csproj
  Web/RDD.Web/Serialization/IRddSerializer.cs
  Web/RDD.Web/Serialization/Providers/ISerializerProvider.cs
  Web/RDD.Web/Serialization/Providers/SerializerProvider.cs
  Web/RDD.Web/Serialization/RddJsonResult.cs
  Web/RDD.Web/Serialization/RddSerializer.cs
  Web/RDD.Web/Serialization/Serializers/ArraySerializer.cs
  Web/RDD.Web/Serialization/Serializers/BaseClassSerializer.cs
  Web/RDD.Web/Serialization/Serializers/CultureInfoSerializer.cs
  Web/RDD.Web/Serialization/Serializers/DateTimeSerializer.cs
  Web/RDD.Web/Serialization/Serializers/DictionarySerializer.cs
  Web/RDD.Web/Serialization/Serializers/EntitySerializer.cs
  Web/RDD.Web/Serialization/Serializers/FuncSerializer.cs
  Web/RDD.Web/Serialization/Serializers/ISerializer.cs
  Web/RDD.Web/Serialization/Serializers/MetadataSerializer.cs
  Web/RDD.Web/Serialization/Serializers/ObjectSerializer.cs
  Web/RDD.Web/Serialization/Serializers/SelectionSerializer.cs
  Web/RDD.Web/Serialization/Serializers/Serializer.cs
  Web/RDD.Web/Serialization/Serializers/ToStringSerializer.cs
  Web/RDD.Web/Serialization/Serializers/ValueSerializer.cs
  docs/CHANGELOG.md
Labels: Breaking changes, enhancement, release 3.0

#194 FIX : utilsier le retour du patcher
  Domain/RDD.Domain.Tests/CollectionMethodsTests.cs
  Domain/RDD.Domain/Models/RestCollection.cs
Labels: bug, release 3.0

#183 OrderBy sur de Guid
  Domain/RDD.Domain.Tests/Models/User.cs
  Domain/RDD.Domain.Tests/OrderByConverterTests.cs
  Domain/RDD.Domain/Models/Querying/OrderBy.cs
  Infra/RDD.Infra.Tests/CollectionTests.cs
  Infra/RDD.Infra.Tests/DatabaseTest.cs
  Infra/RDD.Infra.Tests/UsersRepository.cs
  Web/RDD.Web/Querying/OrderByParser.cs
Labels: bug, release 3.0

#203 MOD : appcontroller utilise simplement un IUnitOfWork
  Application/RDD.Application/Controllers/AppController.cs
  Application/RDD.Application/IUnitOfWork.cs
  Domain/RDD.Domain.Tests/Models/OpenRepository.cs
  Domain/RDD.Domain.Tests/Models/UsersAppController.cs
  Infra/RDD.Infra.Tests/UsersRepository.cs
  Infra/RDD.Infra/Storage/EFStorageService.cs
  Infra/RDD.Infra/Storage/IStorageService.cs
  Infra/RDD.Infra/Storage/InMemoryStorageService.cs
  Web/RDD.Web.Tests/Services/ServicesCollectionTests.cs
  Web/RDD.Web/Helpers/RddServiceCollectionExtensions.cs
  docs/CHANGELOG.md
Labels: Breaking changes, release 3.0

#204 MOD : impossible de savechanges depuis l'infra
  Domain/RDD.Domain.Tests/DefaultFixture.cs
  Infra/RDD.Infra/Storage/EFStorageService.cs
  Infra/RDD.Infra/Storage/IStorageService.cs
  Infra/RDD.Infra/Storage/InMemoryStorageService.cs
  Web/RDD.Web/Helpers/RddServiceCollectionExtensions.cs
  docs/CHANGELOG.md
Labels: Breaking changes, enhancement, release 3.0

#202 REM : 2 fichiers plus utilisés
  Web/RDD.Web/Helpers/ExpressionHelper.cs
  Web/RDD.Web/Helpers/NameValueCollectionHelper.cs
  docs/CHANGELOG.md
Labels: Breaking changes, enhancement, release 3.0

#195 FIX : pb serialization classe dans hierarchy
  Domain/RDD.Domain.Mocks/Hierarchy.cs
  Web/RDD.Web.Tests/Serialization/FieldsTests.cs
  Web/RDD.Web.Tests/Serialization/PropertySerializerTests.cs
  Web/RDD.Web/Helpers/RddServiceCollectionExtensions.cs
  Web/RDD.Web/Serialization/Serializers/BaseClassSerializer.cs
Labels: bug, release 3.0

#225 Performances serialization
  Benchmarks/Rdd.Benchmarks/Rdd.Benchmarks.sln
  Benchmarks/Rdd.Benchmarks/Rdd.Benchmarks/Program.cs
  Benchmarks/Rdd.Benchmarks/Rdd.Benchmarks/Rdd.Benchmarks.csproj
  Benchmarks/Rdd.Benchmarks/Rdd.Benchmarks/RddVsNewtonsoft.cs
  Domain/RDD.Domain.Tests/CollectionMethodsTests.cs
  Domain/RDD.Domain.Tests/DefaultFixture.cs
  Domain/RDD.Domain.Tests/Models/UsersCollection.cs
  Domain/RDD.Domain.Tests/Models/UsersCollectionWithParameters.cs
  Domain/RDD.Domain.Tests/PatchersTests.cs
  Domain/RDD.Domain.Tests/Templates/SingleContextTests.cs
  Domain/RDD.Domain/Helpers/Expressions/EnumerablePropertyExpression.cs
  Domain/RDD.Domain/Helpers/Expressions/ExpressionParser.cs
  Domain/RDD.Domain/Helpers/Expressions/ExpressionTree.cs
  Domain/RDD.Domain/Helpers/Expressions/IExpressionTree.cs
  Domain/RDD.Domain/Helpers/Expressions/PropertyExpression.cs
  Domain/RDD.Domain/Helpers/Expressions/Utils/ExpressionChainExtractor.cs
  Domain/RDD.Domain/Helpers/Reflection/IReflectionHelper.cs
  Domain/RDD.Domain/Helpers/Reflection/ReflectionHelper.cs
  Domain/RDD.Domain/Patchers/BaseClassPatcher.cs
  Domain/RDD.Domain/Patchers/DictionaryPatcher.cs
  Domain/RDD.Domain/Patchers/DynamicPatcher.cs
  Domain/RDD.Domain/Patchers/EnumerablePatcher.cs
  Domain/RDD.Domain/Patchers/ObjectPatcher.cs
  Domain/RDD.Domain/Patchers/PatcherProvider.cs
  Domain/RDD.Domain/Patchers/ValuePatcher.cs
  Domain/RDD.Domain/RDD.Domain.csproj
  Web/RDD.Web.Tests/Models/Department.cs
  Web/RDD.Web.Tests/Serialization/FieldsTests.cs
  Web/RDD.Web.Tests/Serialization/PropertySerializerTests.cs
  Web/RDD.Web/Helpers/RddServiceCollectionExtensions.cs
  Web/RDD.Web/Serialization/Providers/ISerializerProvider.cs
  Web/RDD.Web/Serialization/Providers/SerializerProvider.cs
  Web/RDD.Web/Serialization/RddJsonResult.cs
  Web/RDD.Web/Serialization/Reflection/IReflectionProvider.cs
  Web/RDD.Web/Serialization/Reflection/ReflectionProvider.cs
  Web/RDD.Web/Serialization/Serializers/ArraySerializer.cs
  Web/RDD.Web/Serialization/Serializers/BaseClassSerializer.cs
  Web/RDD.Web/Serialization/Serializers/CultureInfoSerializer.cs
  Web/RDD.Web/Serialization/Serializers/DateTimeSerializer.cs
  Web/RDD.Web/Serialization/Serializers/DictionarySerializer.cs
  Web/RDD.Web/Serialization/Serializers/EntitySerializer.cs
  Web/RDD.Web/Serialization/Serializers/FuncSerializer.cs
  Web/RDD.Web/Serialization/Serializers/MetadataSerializer.cs
  Web/RDD.Web/Serialization/Serializers/ObjectSerializer.cs
  Web/RDD.Web/Serialization/Serializers/SelectionSerializer.cs
  Web/RDD.Web/Serialization/Serializers/ValueSerializer.cs
  docs/CHANGELOG.md
Labels: enhancement

#212 MOD : Ientitybase light pass
  Application/RDD.Application/Controllers/AppController.cs
  Application/RDD.Application/IAppController.cs
  Domain/RDD.Domain.Mocks/Hierarchy.cs
  Domain/RDD.Domain.Tests/Models/DataContext.cs
  Domain/RDD.Domain.Tests/Models/TablePerHierarchyModel.cs
  Domain/RDD.Domain.Tests/Models/User.cs
  Domain/RDD.Domain.Tests/Models/UserWithParameters.cs
  Domain/RDD.Domain/IEntityBase.cs
  Domain/RDD.Domain/IPrimaryKey.cs
  Domain/RDD.Domain/Models/EntityBase.cs
  Domain/RDD.Domain/Models/RestCollection.cs
  Infra/RDD.Infra/Storage/InMemoryStorageService.cs
  Web/RDD.Web.Tests/Models/AnotherUser.cs
  Web/RDD.Web.Tests/Models/Department.cs
  Web/RDD.Web.Tests/Models/IUser.cs
  Web/RDD.Web.Tests/Models/User.cs
  Web/RDD.Web.Tests/ServerMock/ExchangeRate.cs
  Web/RDD.Web.Tests/Services/ServicesCollectionTests.cs
  Web/RDD.Web/Controllers/ReadOnlyWebController.cs
  Web/RDD.Web/Controllers/WebController.cs
  Web/RDD.Web/Helpers/RddServiceCollectionExtensions.cs
  docs/CHANGELOG.md
Labels: Breaking changes, enhancement

#211 REF méthodes AddRddXXX
  Domain/RDD.Domain.Mocks/CombinationsHolderMock.cs
  Domain/RDD.Domain.Mocks/PrincipalMock.cs
  Domain/RDD.Domain.Tests/AbstractEntityTests.cs
  Domain/RDD.Domain.Tests/CollectionMethodsTests.cs
  Domain/RDD.Domain.Tests/DefaultFixture.cs
  Domain/RDD.Domain.Tests/ExceptionTests.cs
  Domain/RDD.Domain.Tests/Models/DataContext.cs
  Domain/RDD.Domain.Tests/Models/Hierarchy.cs
  Domain/RDD.Domain.Tests/RDD.Domain.Tests.csproj
  Domain/RDD.Domain.Tests/RightExpressionsHelperTests.cs
  Domain/RDD.Domain.Tests/Templates/SingleContextTests.cs
  Domain/RDD.Domain/Exceptions/UnreachableEntityException.cs
  Domain/RDD.Domain/IPrincipal.cs
  Domain/RDD.Domain/Models/Querying/Page.cs
  Domain/RDD.Domain/Models/ReadOnlyRestCollection.cs
  Domain/RDD.Domain/Rights/ClosedRightExpressionsHelper.cs
  Domain/RDD.Domain/Rights/ICombinationsHolder.cs
  Domain/RDD.Domain/Rights/OpenRightExpressionsHelper.cs
  Domain/RDD.Domain/Rights/RightDefaultMode.cs
  Domain/RDD.Domain/Rights/RightExpressionsHelper.cs
  Infra/RDD.Infra/Storage/ReadOnlyRepository.cs
  RDD.sln
  Web/RDD.Web.Tests/ApiHelperTests.cs
  Web/RDD.Web.Tests/CandidateTests.cs
  Web/RDD.Web.Tests/CollectionPropertiesTests.cs
  Web/RDD.Web.Tests/FilterParserTests.cs
  Web/RDD.Web.Tests/Models/UserWebController.cs
  Web/RDD.Web.Tests/RDD.Web.Tests.csproj
  Web/RDD.Web.Tests/Serialization/FieldsTests.cs
  Web/RDD.Web.Tests/Serialization/PropertySerializerTests.cs
  Web/RDD.Web.Tests/ServerMock/CombinationsHolder.cs
  Web/RDD.Web.Tests/ServerMock/CurPrincipal.cs
  Web/RDD.Web.Tests/ServerMock/Startup.cs
  Web/RDD.Web.Tests/Services/ServicesCollectionTests.cs
  Web/RDD.Web.Tests/WebControllerTests.cs
  Web/RDD.Web.Tests/WebPagingTests.cs
  Web/RDD.Web/Helpers/ApiHelper.cs
  Web/RDD.Web/Helpers/RddBuilder.cs
  Web/RDD.Web/Helpers/RddOptions.cs
  Web/RDD.Web/Helpers/RddServiceCollectionExtensions.cs
  Web/RDD.Web/Models/Metadata.cs
  Web/RDD.Web/Models/MetadataHeader.cs
  Web/RDD.Web/Querying/WebPage.cs
  Web/RDD.Web/Querying/WebPageParser.cs
  Web/RDD.Web/Querying/WebQuery.cs
  Web/RDD.Web/Querying/WebQueryFactory.cs
  Web/RDD.Web/Serialization/RddJsonResult.cs
  docs/CHANGELOG.md
Labels: Breaking changes, bug, clean.code, release 3.0

#223 Validation consistency
  Domain/RDD.Domain/IRepository.cs
  Domain/RDD.Domain/Models/RestCollection.cs
  Infra/RDD.Infra/Storage/EFStorageService.cs
  Infra/RDD.Infra/Storage/IStorageService.cs
  Infra/RDD.Infra/Storage/InMemoryStorageService.cs
  Infra/RDD.Infra/Storage/Repository.cs
  Web/Rdd.Web.Tests/ValidationTests.cs
  docs/CHANGELOG.md
Labels: enhancement, release 3.0

#224 Adds AppController AfterGet, BeforeSave and AfterSave methods
  Application/RDD.Application/Controllers/AppController.cs
  Application/RDD.Application/Controllers/ReadOnlyAppController.cs
  Domain/Rdd.Domain/Helpers/IEnumerableExtensions.cs
  docs/CHANGELOG.md
Labels: enhancement, release 3.0

#231 Fichiers inutilisés
  src/Rdd.Domain/Helpers/Culture.cs
  test/Rdd.Domain.Tests/Templates/SingleContextTests.cs
Labels: clean.code, release 3.0

#243 FIX : protection contre un bug EF + evaluation client EF dans le plus…
  src/Rdd.Infra/Helpers/WebFilterConverter.cs
  test/Rdd.Web.Tests/QueryBuilderTests.cs
Labels: bug, enhancement, release 3.0

#244 Rdd register issues
  docs/CHANGELOG.md
  src/Rdd.Domain/Patchers/PatcherProvider.cs
  src/Rdd.Web/Helpers/RddServiceCollectionExtensions.cs
  src/Rdd.Web/Serialization/Providers/SerializerProvider.cs
  src/Rdd.Web/Serialization/RddJsonResult.cs
  test/Rdd.Web.Tests/Services/ServicesCollectionTests.cs
Labels: bug, release 3.0

#233 Reduce allocations on string comparisons
  src/Rdd.Domain/Json/JsonParser.cs
  src/Rdd.Domain/Patchers/BaseClassPatcher.cs
  src/Rdd.Web/Serialization/Serializers/CultureInfoSerializer.cs
Labels: enhancement, release 3.0

#232 Ef storage.cleanup
  docs/CHANGELOG.md
  src/Rdd.Infra/Storage/EFStorageService.cs
Labels: clean.code, release 3.0

#230 Code cleanups
  src/Rdd.Application/Controllers/ReadOnlyAppController.cs
  src/Rdd.Domain/Helpers/Expressions/Equality/ConstantValue.cs
  src/Rdd.Domain/Helpers/Expressions/Equality/ExpressionHashCodeResolver.cs
  src/Rdd.Domain/Helpers/Expressions/ExpressionParser.cs
  src/Rdd.Domain/Helpers/Expressions/Utils/TreeParser.cs
  src/Rdd.Domain/Helpers/Reflection/ReflectionHelper.cs
  src/Rdd.Domain/Json/JsonArray.cs
  src/Rdd.Domain/Json/JsonElement.cs
  src/Rdd.Domain/Json/JsonObject.cs
  src/Rdd.Domain/Json/JsonParser.cs
  src/Rdd.Domain/Json/JsonValue.cs
  src/Rdd.Domain/Models/Querying/OrderBy.cs
  src/Rdd.Domain/Patchers/DictionaryPatcher.cs
  src/Rdd.Domain/Patchers/EnumerablePatcher.cs
  src/Rdd.Domain/Patchers/IPatcher.cs
  src/Rdd.Domain/Patchers/ObjectPatcher.cs
  src/Rdd.Domain/Patchers/PatcherProvider.cs
  src/Rdd.Domain/Patchers/ValuePatcher.cs
  src/Rdd.Infra/Storage/EFStorageService.cs
  src/Rdd.Infra/Storage/IStorageService.cs
  src/Rdd.Infra/Storage/InMemoryStorageService.cs
  src/Rdd.Infra/Storage/ReadOnlyRepository.cs
  src/Rdd.Infra/Storage/Repository.cs
  src/Rdd.Web/Querying/QueryParser.cs
  src/Rdd.Web/Serialization/Providers/SerializerProvider.cs
  src/Rdd.Web/Serialization/Serializers/BaseClassSerializer.cs
  test/Rdd.Domain.Tests/CollectionMethodsTests.cs
  test/Rdd.Domain.Tests/DictionaryPropertySelectorTests.cs
  test/Rdd.Domain.Tests/Members/ExpressionChainExtractorTests.cs
  test/Rdd.Domain.Tests/Members/ExpressionChainerTests.cs
  test/Rdd.Domain.Tests/Members/ExpressionEqualityTests.cs
  test/Rdd.Domain.Tests/Members/ExpressionTreeTests.cs
  test/Rdd.Domain.Tests/Models/CustomField.cs
  test/Rdd.Domain.Tests/Models/EnumClient.cs
  test/Rdd.Domain.Tests/Models/ICodable.cs
  test/Rdd.Domain.Tests/PatchersTests.cs
  test/Rdd.Domain.Tests/PropertySelectorCollectionTests.cs
  test/Rdd.Web.Tests/CandidateTests.cs
  test/Rdd.Web.Tests/CollectionPropertiesTests.cs
  test/Rdd.Web.Tests/OptionsParserTests.cs
  test/Rdd.Web.Tests/QueryParserHelper.cs
  test/Rdd.Web.Tests/QueryParserTests.cs
  test/Rdd.Web.Tests/Serialization/PropertySerializerTests.cs
  test/Rdd.Web.Tests/Services/ServicesCollectionTests.cs
  test/Rdd.Web.Tests/ValidationTests.cs
  test/Rdd.Web.Tests/WebPagingTests.cs
Labels: clean.code, release 3.0

#245 REM : EntityBase.Url set
  src/Rdd.Domain/Models/EntityBase.cs
  src/Rdd.Domain/Patchers/ObjectPatcher.cs
  test/Rdd.Domain.Tests/Models/User.cs
  test/Rdd.Domain.Tests/PatchersTests.cs
  test/Rdd.Web.Tests/ExchangeRateIntegrationTest.cs
  test/Rdd.Web.Tests/Serialization/PropertySerializerTests.cs
  test/Rdd.Web.Tests/Serialization/UrlProviderTests.cs
Labels: bug, enhancement, release 3.0

#254 MOD : default paging on get only
  src/Rdd.Web/Querying/QueryParser.cs
  src/Rdd.Web/Querying/WebPageParser.cs
  test/Rdd.Web.Tests/QueryParserTests.cs
Labels: bug

#249 MOD : implémentation de iurlprovider
  docs/CHANGELOG.md
  src/Rdd.Web/Helpers/RddServiceCollectionExtensions.cs
  src/Rdd.Web/Rdd.Web.csproj
  src/Rdd.Web/Serialization/UrlProviders/IPluralizationService.cs
  src/Rdd.Web/Serialization/UrlProviders/IUrlProvider.cs
  src/Rdd.Web/Serialization/UrlProviders/PluralizationService.cs
  src/Rdd.Web/Serialization/UrlProviders/UrlProvider.cs
  test/Rdd.Web.Tests/ExceptionIntegrationTest.cs
  test/Rdd.Web.Tests/ExchangeRateIntegrationTest.cs
  test/Rdd.Web.Tests/PluralizationServiceTests.cs
  test/Rdd.Web.Tests/Serialization/FieldsTests.cs
  test/Rdd.Web.Tests/Serialization/UrlProviderTests.cs
  test/Rdd.Web.Tests/ServerMock/ExchangeRate.cs
  test/Rdd.Web.Tests/ServerMock/ExchangeRateController.cs
  test/Rdd.Web.Tests/ServerMock/ExchangeRateDbContext.cs
  test/Rdd.Web.Tests/ServerMock/Startup.cs
Labels: enhancement, release 3.0

#256 FIX : super class deserialization
  src/Rdd.Domain/Patchers/BaseClassPatcher.cs
  src/Rdd.Web/Querying/Candidate.cs
  src/Rdd.Web/Querying/CandidateParser.cs
  test/Rdd.Domain.Tests/AppControllerTests.cs
  test/Rdd.Domain.Tests/CollectionMethodsTests.cs
  test/Rdd.Domain.Tests/Models/Hierarchy.cs
  test/Rdd.Web.Tests/ApiHelperTests.cs
  test/Rdd.Web.Tests/BeforeAfterSaveChangesValidation.cs
  test/Rdd.Web.Tests/CandidateTests.cs
  test/Rdd.Web.Tests/ValidationTests.cs
Labels: bug

#257 ADD : utility methods on RddBuilder
  src/Rdd.Domain/Patchers/PatcherProvider.cs
  src/Rdd.Web/Helpers/RddBuilderExtensions.cs
  src/Rdd.Web/Helpers/RddServiceCollectionExtensions.cs
  test/Rdd.Web.Tests/Services/RddBuilderTests.cs
  test/Rdd.Web.Tests/Services/ServicesCollectionTests.cs
Labels: enhancement

#248 ADD : api/controller comme default route
  src/Rdd.Web/Controllers/ReadOnlyWebController.cs
  test/Rdd.Web.Tests/ApiExplorerTests.cs
  test/Rdd.Web.Tests/ServerMock/ExchangeRateController.cs
Labels: bug
