Repository LuccaSA/RestDrivenDomain, pull requests merged in 2018-09, with the labels that each got.

#161 Create en masse, throw from web et autres..
  Application/RDD.Application/Controllers/AppController.cs
  Application/RDD.Application/IAppController.cs
  Domain/RDD.Domain.Tests/AppControllerTests.cs
  Domain/RDD.Domain.Tests/CollectionMethodsTests.cs
  Domain/RDD.Domain/Exceptions/NotFoundException.cs
  Domain/RDD.Domain/IRestCollection.cs
  Domain/RDD.Domain/Models/ReadOnlyRestCollection.cs
  Domain/RDD.Domain/Models/RestCollection.cs
  Web/RDD.Web/Controllers/ReadOnlyWebController.cs
  Web/RDD.Web/Controllers/WebController.cs
Labels: Breaking changes, release 3.0

#163 MOD : pas de paging sur les requêtes internes + getAll/CountAll
  Domain/RDD.Domain.Tests/AbstractEntityTests.cs
  Domain/RDD.Domain/IReadOnlyRestCollection.cs
  Domain/RDD.Domain/Models/Querying/Page.cs
  Domain/RDD.Domain/Models/Querying/Query.cs
  Domain/RDD.Domain/Models/ReadOnlyRestCollection.cs
  Infra/RDD.Infra/Storage/ReadOnlyRepository.cs
Labels: Breaking changes, enhancement, release 3.0

#165 ADD : changelog
  docs/CHANGELOG.md
Labels: enhancement, release 3.0

#167 ADD WebQuery : différenciation du paging
  CHANGELOG.md
  Domain/RDD.Domain.Tests/CollectionMethodsTests.cs
  Domain/RDD.Domain/Models/Querying/Page.cs
  Domain/RDD.Domain/Models/Querying/Query.cs
  Web/RDD.Web.Tests/CollectionPropertiesTests.cs
  Web/RDD.Web.Tests/Models/IUserWebController.cs
  Web/RDD.Web.Tests/RDD.Web.Tests.csproj
  Web/RDD.Web.Tests/WebPagingTests.cs
  Web/RDD.Web/Helpers/ApiHelper.cs
  Web/RDD.Web/Querying/WebPage.cs
  Web/RDD.Web/Querying/WebPageParser.cs
  Web/RDD.Web/Querying/WebQuery.cs
  Web/RDD.Web/Querying/WebQueryFactory.cs
  docs/CHANGELOG.md
Labels: enhancement, release 3.0

#151 ADD : support de l'héritage dans RDD
  Domain/RDD.Domain.Mocks/Hierarchy.cs
  Domain/RDD.Domain.Tests/CollectionMethodsTests.cs
  Domain/RDD.Domain.Tests/Models/DataContext.cs
  Domain/RDD.Domain/IInheritanceConfiguration.cs
  Domain/RDD.Domain/Models/BaseClassInstanciator.cs
  Domain/RDD.Domain/Patchers/BaseClassPatcher.cs
  Web/RDD.Web.Tests/CandidateTests.cs
  Web/RDD.Web.Tests/OptionsParserTests.cs
  Web/RDD.Web.Tests/RDD.Web.Tests.csproj
  Web/RDD.Web.Tests/Serialization/FieldsTests.cs
  Web/RDD.Web.Tests/Serialization/PropertySerializerTests.cs
  Web/RDD.Web.Tests/Services/ServicesCollectionTests.cs
  Web/RDD.Web/Helpers/RddServiceCollectionExtensions.cs
  Web/RDD.Web/Models/BaseClassJsonConverter.cs
  Web/RDD.Web/Querying/FieldsParser.cs
  Web/RDD.Web/Querying/WebQueryFactory.cs
  Web/RDD.Web/Serialization/BaseClassSerializer.cs
  Web/RDD.Web/Serialization/Providers/SerializerProvider.cs
  docs/CHANGELOG.md
Labels: enhancement

#166 Tests
  Domain/RDD.Domain.Mocks/CombinationsHolderMock.cs
  Domain/RDD.Domain.Tests/CollectionMethodsTests.cs
  Domain/RDD.Domain.Tests/ExceptionTests.cs
  Domain/RDD.Domain.Tests/JsonTests.cs
  Domain/RDD.Domain.Tests/Members/ExpressionEqualityTests.cs
  Domain/RDD.Domain.Tests/PatchersTests.cs
  Domain/RDD.Domain.Tests/PropertySelectorEqualityComparerTests.cs
  Domain/RDD.Domain.Tests/RDD.Domain.Tests.csproj
  Domain/RDD.Domain.Tests/RightExpressionsHelperTests.cs
  Domain/RDD.Domain/Attributes/CulturedDescriptionAttribute.cs
  Domain/RDD.Domain/Contexts/CultureContext.cs
  Domain/RDD.Domain/Exceptions/BadRequestException.cs
  Domain/RDD.Domain/Exceptions/BusinessException.cs
  Domain/RDD.Domain/Exceptions/ForbiddenException.cs
  Domain/RDD.Domain/Exceptions/OutOfRangeException.cs
  Domain/RDD.Domain/Exceptions/TechnicalException.cs
  Domain/RDD.Domain/Exceptions/UnauthorizedException.cs
  Domain/RDD.Domain/Exceptions/UnreachableEntityException.cs
  Domain/RDD.Domain/Exceptions/UnsupportedContentTypeException.cs
  Domain/RDD.Domain/GlobalSuppressions.cs
  Domain/RDD.Domain/Helpers/Expressions/EnumerablePropertyExpression.cs
  Domain/RDD.Domain/Helpers/Expressions/Equality/ExpressionEqualityComparer.cs
  Domain/RDD.Domain/Helpers/Expressions/Equality/ExpressionHashCodeResolver.cs
  Domain/RDD.Domain/Helpers/Expressions/Equality/ExpressionValueComparer.cs
  Domain/RDD.Domain/Helpers/Expressions/ExpressionParser.cs
  Domain/RDD.Domain/Helpers/Expressions/ExpressionTree.cs
  Domain/RDD.Domain/Helpers/Expressions/RddExpressionEqualityComparer.cs
  Domain/RDD.Domain/IDownloadableEntity.cs
  Domain/RDD.Domain/IEntityBase.cs
  Domain/RDD.Domain/IIncludable.cs
  Domain/RDD.Domain/IWebServicesCollection.cs
  Domain/RDD.Domain/Json/IJsonElement.cs
  Domain/RDD.Domain/Json/JsonArray.cs
  Domain/RDD.Domain/Json/JsonElement.cs
  Domain/RDD.Domain/Json/JsonObject.cs
  Domain/RDD.Domain/Json/JsonParser.cs
  Domain/RDD.Domain/Json/JsonValue.cs
  Domain/RDD.Domain/Models/Application.cs
  Domain/RDD.Domain/Models/Combination.cs
  Domain/RDD.Domain/Models/EntityBase.cs
  Domain/RDD.Domain/Models/Enum.cs
  Domain/RDD.Domain/Models/Period.cs
  Domain/RDD.Domain/Models/Querying/Page.cs
  Domain/RDD.Domain/Patchers/DynamicPatcher.cs
  Domain/RDD.Domain/Patchers/EntitiesPatcher.cs
  Domain/RDD.Domain/Patchers/EnumerablePatcher.cs
  Domain/RDD.Domain/Patchers/PatcherProvider.cs
  Domain/RDD.Domain/Rights/ICombinationsHolder.cs
  Domain/RDD.Domain/WebServices/WebService.cs
  Domain/RDD.Domain/WebServices/WebServicesCollection.cs
  Infra/RDD.Infra/Exceptions/QueryBuilderException.cs
  Infra/RDD.Infra/Helpers/QueryBuilder.cs
  Web/RDD.Web.Tests/ServerMock/CombinationsHolder.cs
  Web/RDD.Web.Tests/ServerMock/Startup.cs
  Web/RDD.Web.Tests/WebPagingTests.cs
  docs/CHANGELOG.md
Labels: Breaking changes, enhancement, release 3.0
