Repository LuccaSA/RestDrivenDomain, pull requests merged in 2019-02, with the labels that each got.

#301 Fix perf any
  src/Rdd.Domain/IReadOnlyRepository.cs
  src/Rdd.Domain/Models/ReadOnlyRestCollection.cs
  src/Rdd.Infra/Storage/EFStorageService.cs
  src/Rdd.Infra/Storage/IStorageService.cs
  src/Rdd.Infra/Storage/InMemoryStorageService.cs
  src/Rdd.Infra/Storage/ReadOnlyRepository.cs
  test/Rdd.Infra.Tests/CollectionTests.cs
  test/Rdd.Infra.Tests/Storage/StorageTests.cs
  test/Rdd.Web.Tests/Services/RddBuilderTests.cs
Labels: enhancement

#302 Maj readme
  README.md
Labels: docs

#307 MOD : Apply AsNoTracking by default on Get web request.
  docs/CHANGELOG.md
  src/Rdd.Domain/Models/Querying/Options.cs
  src/Rdd.Domain/Models/ReadOnlyRestCollection.cs
  src/Rdd.Infra/Storage/ReadOnlyRepository.cs
  src/Rdd.Web/Querying/QueryParser.cs
  test/Rdd.Domain.Tests/AppControllerTests.cs
  test/Rdd.Domain.Tests/CollectionMethodsTests.cs
  test/Rdd.Infra.Tests/CollectionTests.cs
  test/Rdd.Web.Tests/Models/UserWebController.cs
  test/Rdd.Web.Tests/OptionsParserTests.cs
  test/Rdd.Web.Tests/QueryParserTests.cs
Labels: 3.1, Breaking changes, enhancement

#305 IUrlProvider : adds test for new endpoint routing support
  test/Rdd.Web.Tests/ApiExplorerTests.cs
  test/Rdd.Web.Tests/ExceptionIntegrationTest.cs
  test/Rdd.Web.Tests/ExchangeRateIntegrationTest.cs
  test/Rdd.Web.Tests/Serialization/UrlProviderTests.cs
  test/Rdd.Web.Tests/ServerMock/Startup.cs
Labels: enhancement

#311 try fix sonar
  appveyor.yml
Labels: bug
